### PR TITLE
Revert "upgrade to django 1.8"

### PR DESCRIPTION
**Pull request by muhammad-ammar**
Reverts edx/edx-search#32

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@wedaly @symbolist @macdiesel @muzaffaryousaf 

accidentally merged :(

**Comment by muzaffaryousaf** [comment]
:+1:

**Comment by muhammad-ammar** [comment]
should i merge?

**Comment by symbolist** [comment]
Yes.

**Pull request merged**
