### PR TITLE
[INCR-102] fix python-3.6 compatibility

### PR DESCRIPTION
**Pull request by singuliere**
Fixes: https://openedx.atlassian.net/browse/INCR-102

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @singuliere! I've created [OSPR-3201](https://openedx.atlassian.net/browse/OSPR-3201) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@singuliere Thank you for your contribution. Please let me know once tests pass and it is ready to be looked at.

**Comment by singuliere** [comment]
This coverage breakage is super weird, I like it. It is something in the python 3.6 virtualenv that breaks `coverage report`.

```
singuliere@raise:~/software/openedx/edx-search$ .tox/py36-django111/bin/python3.6 .tox/py36-django111/bin/coverage report
Name                                           Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------------------
search/__init__.py                                 0      0      0      0   100%
search/api.py   KeyError: 29820
search/elastic.py   KeyError: 31830
search/filter_generator.py   KeyError: 31776
search/initializer.py                              9      0      0      0   100%
search/result_processor.py   KeyError: 25614
search/search_engine_base.py   KeyError: 31776
search/tests/__init__.py                           0      0      0      0   100%
search/tests/mock_search_engine.py   KeyError: 25620
search/tests/test_course_discovery.py   KeyError: 29730
search/tests/test_course_discovery_views.py   KeyError: 32023
search/tests/test_engines.py   IndexError: pop from empty list
search/tests/test_mock_search_engine.py           56      0      2      0   100%
search/tests/test_search_result_processor.py   KeyError: 25620
search/tests/test_views.py   KeyError: 557
search/tests/tests.py   KeyError: 32023
search/tests/utils.py   KeyError: 29718
search/urls.py                                     6      0      0      0   100%
search/utils.py   KeyError: 31809
search/views.py   IndexError: pop from empty list
--------------------------------------------------------------------------------
TOTAL                                             71      0      2      0   100%
singuliere@raise:~/software/openedx/edx-search$ /usr/bin/python3.6 .tox/py36-django111/bin/coverage report
Name                                           Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------------------
search/__init__.py                                 0      0      0      0   100%
search/api.py                                     41      0     18      0   100%
search/elastic.py                                184      0     92      3    99%
search/filter_generator.py                        17      0      2      0   100%
search/initializer.py                              9      0      0      0   100%
search/result_processor.py                        79      0     35      0   100%
search/search_engine_base.py                      22      0      2      1    96%
search/tests/__init__.py                           0      0      0      0   100%
search/tests/mock_search_engine.py               232      0    142      5    99%
search/tests/test_course_discovery.py            205      0     20      1    99%
search/tests/test_course_discovery_views.py       99      0     20      0   100%
search/tests/test_engines.py                     134      0     12      0   100%
search/tests/test_mock_search_engine.py           56      0      2      0   100%
search/tests/test_search_result_processor.py     123      0      6      0   100%
search/tests/test_views.py                       241      0     34      0   100%
search/tests/tests.py                            559      0     52      0   100%
search/tests/utils.py                             38      0      2      0   100%
search/urls.py                                     6      0      0      0   100%
search/utils.py                                   29      0      2      0   100%
search/views.py                                   69      0     18      0   100%
--------------------------------------------------------------------------------
TOTAL                                           2143      0    459     10    99%
singuliere@raise:~/software/openedx/edx-search$ md5sum /usr/bin/python3.6
3c1aa88beda7c454901a5f8e692d3007  /usr/bin/python3.6
singuliere@raise:~/software/openedx/edx-search$ md5sum .tox/py36-django111/bin/python3.6
3c1aa88beda7c454901a5f8e692d3007  .tox/py36-django111/bin/python3.6
```

**Comment by singuliere** [comment]
@natabene although it's WIP I need advice from a reviewer on the errors I get. A quick look would be enough. I'm not asking for a solution. I'm curious if the reviewer already had that kind of errors. Although I could work on fixing them, I feel like I'm missing something really simple.

**Comment by singuliere** [comment]
The coverage is lower because there now are lines only run via python3 and lines only run via python2. Since the coverage data is not consolidated accross python3 / python2 runs, it is mistaken to be lower coverage.

**Comment by singuliere** [comment]
@natabene nevermind, I figured it out :-) It's just a matter of upgrading coverage

**Comment by edx-webhook** [comment]
@singuliere 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-search&entry.867055334=https://github.com/edx/edx-search/pull/73&entry.1484655318=https://github.com/singuliere&entry.752974735=2019-03-13+15:22&entry.1917517419=2019-03-18+21:26&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
