### PR TITLE
upgrade to django 1.8

### PR DESCRIPTION
**Pull request by muhammad-ammar**
TNL-2826

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@wedaly @symbolist @muzaffaryousaf @macdiesel Please have a look. Thanks

**Comment by symbolist** [comment]
:+1:

**Comment by muhammad-ammar** [comment]
@wedaly ^^

**Comment by macdiesel** [comment]
Need to bump up the version in setup.py

**Comment by wedaly** [comment]
Simple enough.  :+1: once the version is bumped.

**Pull request merged**
